# Generated by Django 5.0.6 on 2024-06-05 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemodul',
            name='files',
        ),
    ]
