# Generated by Django 5.0.6 on 2024-06-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='videos',
            field=models.FileField(blank=True, null=True, upload_to='video'),
        ),
    ]
