# Generated by Django 5.0.6 on 2024-06-06 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_quiz_quizchoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lang', to='course.languages'),
        ),
    ]
